language: java
jdk: oraclejdk8
branches:
  only:
  - master
addons:
  sonarcloud:
    organization: crerader-github
    token:
      secure: e84f6540d936717fcd9678766f72e0a816362e0d
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
after_deploy:
- echo "done deploying"
