language: java
jdk: oraclejdk8
branches:
  only:
  - master
addons:
  sonarcloud:
    organization: crerader-github
    token:
      secure: M5FqV9Auc3yoxRMP9c24oKPDqayLp54AZOshBYYydA0OM/JoSSBxBcOnpWM3OAYRPXe9kUIWdVlllYwI3k0K5QjJ613YZMxpUqgo1Z0WuZR/R7nKGOG8akTCm5qZPlbmthQcoIqOdxMe6Y0X668T1LosszvObmf3IQuX/ZVAPUYjIFx14WHg6GLv+Wn0s+pjAbM0so1722Ml0KHuZSQ0LLxH48pRFHW4bSHSsMFOcxUA+pPtGxgMUYdY0Cp8s2NCFXRfpEx3BEDCvQ/5CrYHX5ew67QrQMrHZMowCDifPQlksaxY0XQuVqlcov7jpZBlnJaw7axLRX3b7P3NyKEWYnbn/3jbeadQFnq3VKMQRtkXORfwttGesjQnJsfKUbMOwPIN6pLVKJAPrsGYXzP30aJjO0EIM6Db37Pb0/Uyc+EJL8pXBsRnXI2fDRNMQlHZnw25s0k1wnc6y/ELF0CwoE6Oso25TFvHw41N299wIq8KJdhIT+1KOLeM0VLUac770KvHk5BOxBZCDdZeO4ETEbEOIhE8ad5PCPt3rkcGBDrVUwLXSBjKJOSvaPMemobWqPQlnxdAuhiHL2Ua3pRh4KvQbukXHB0O8syEjHF1ht9x/nt9iv+zgfM63WU4LcM2REvsfIbg9vEEj0GwxcuJCRT68McOzkQTBmPUG0+ytJ0=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
after_deploy:
- echo "done deploying"
